# Generated by Django 5.1.1 on 2024-09-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_post_id_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='polarity',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sender_name',
            field=models.TextField(max_length=100),
        ),
    ]
