# Generated by Django 5.1.1 on 2024-09-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comment_polarity_alter_comment_sender_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='polarity',
        ),
    ]
