# Generated by Django 5.1.1 on 2024-10-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_comment_polarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='polarity',
            field=models.CharField(default='Нейтральный', max_length=100),
        ),
    ]
